# Generated by Django 3.0.8 on 2020-11-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='test@email.com', max_length=254)),
                ('phone', models.IntegerField(default=234099940409)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Billing Addresses',
            },
        ),
    ]
