# Generated by Django 3.1.3 on 2020-11-02 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='user',
        ),
    ]
